version: "3"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: sap-hana-database-egress
      MODULE_TYPE: EGRESS
      EGRESS_URL: None
      INGRESS_HOST: 0.0.0.0
      INGRESS_PORT: 80
      INGRESS_PATH: /
      HDB_ADDRESS: f4a3724b752e.hana.us10.hanacloud.com
      HDB_PORT: 443
      HDB_USER: user
      HDB_PASSWORD: password
      HDB_SCHEMA: schema
      HDB_TABLE: table
      HDB_HEADERS: "temp, text, rand"
      LABELS: "temp, test, random"
    ports:
      - 5000:80
