version: "3.0"
services:
  sap-hana-database-egress:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: sap-hana-database-egress
      MODULE_TYPE: Output
      INGRESS_HOST: 0.0.0.0
      INGRESS_PORT: 80
      HDB_ADDRESS: f4a3724b752e.hana.us10.hanacloud.com
      HDB_PORT: 443
      HDB_USER: user
      HDB_PASSWORD: password
      HDB_SCHEMA: schema
      HDB_TABLE: table
      HDB_HEADERS: "temp, text, rand"
      LABELS: "temp, test, random"
    ports:
      - 80:80
